### PR TITLE
Use FQCNs for M() references

### PR DESCRIPTION
**Pull request by bmillemathias**
See https://github.com/ansible-collections/overview/issues/89

### CODE REVIEW

**Comment by bmillemathias** [comment]
Hello, 

The PR was closed without any reason, can you explain ?

thanks

**Comment by wojtek0806** [comment]
Read the readme, submit issue not PRs

**Comment by bmillemathias** [comment]
There nothing stating no PR should be opened

**Comment by wojtek0806** [comment]
Screen Shot 2020-07-13 at 15 59 09

**Comment by bmillemathias** [comment]
so this PR was just to fix interlink to be compatible with ansible documentation, but this is not to a concern for you, have a nice day.

**Comment by focrensh** [comment]
We appreciate the help here. We will take note from the PR until we are able to accept them.

**Pull request closed without merging**
