### PR TITLE
Enabled Route Domain Functionality

### PR DESCRIPTION
**Pull request by manuadoor**
I have enabled the optional functionality of creating self IP for a specific route domain. Please review and consider approving the pull request.

- Manu Pillai 

Example: 

 - name: Create Self IP with a Route Domain
   bigip_selfip:
     server: "lb.mydomain.com"
     user: "admin"
     password: "secret"
     validate_certs: "no"
     name: "self1"
     address: "10.10.10.10"
     netmask: "255.255.255.0"
     vlan: "vlan1"
     rd: "10"
     allow_service: "default"
   delegate_to: localhost

### CODE REVIEW

**Comment by caphrim007** [comment]
@manuadoor so to make this work we only need to append the route domain to the ip? is that correct?

**Comment by manuadoor** [comment]
Thats correct.. we will pass an optional parameter "rd" for route domain id and self IP will be created for that rd.

**Comment by caphrim007** [comment]
ok, gotcha. this PR needs to be rebased to take into account the recent traffic class additions. can you rebase from the current master branch?

**Comment by manuadoor** [comment]
Alright, I will take a look at it soon

**Comment by manuadoor** [comment]
I just checked, you are talking about the last commit (https://github.com/F5Networks/f5-ansible/pull/31/commits/114a082d93b59e2490a5a8d67c247e6a2f51274e) 6 days ago ? if yes, it is based on that commit.

**Comment by caphrim007** [comment]
yes, but PR's need to not show those changes that I made, they must only show the changes you made. The PR you have here shows both my changes as well as your changes.

**Pull request closed without merging**
