### PR TITLE
request to add bigip_ssl_certificate and bigip_ssl_profile

### PR DESCRIPTION
**Pull request by waffie1**
I have created 2 new modules which I am requesting be added.

bigip_ssl_certificate is a module to import/delete certificates from pem or p12 file from local(ansible host) files.

bigip_ssl_profile is a module to create/manage ssl profiles.  Currently only clientssl is supported, with limited options implemented.  Will add more options and serverssl as time permits.

Both modules require bigsuds as f5-sdk is missing support needed to implement these functions.  I've tried my best to remove bigsuds specific logic from the main function to hopefully make implementing REST easier when sdk support is there.

### CODE REVIEW

**Comment by caphrim007** [comment]
@waffie1 Can you check the most recent version of f5-sdk to see if SSL certs are now available? I remember seeing a merge go through the other day with this functionality.

https://github.com/F5Networks/f5-common-python/pull/420

**Comment by waffie1** [comment]
A quick glance looks like things are there now.  I'll work on this and see
if everything needed is there and working.

**Comment by caphrim007** [comment]
thanks @waffie1.  If there is missing functionality, can you open an issue on their repo there so I can add the necessary code?

**Comment by waffie1** [comment]
Closing this request.  I am working on rewrite to support f5-sdk for both modules.   Will re-up when complete.

**Pull request closed without merging**
