### PR TITLE
adding validation to the IP address param and compressing for IPv6 checking

### PR DESCRIPTION
**Pull request by champain**
I'm not sure I did this right, but this is in response to https://github.com/F5Networks/f5-ansible/issues/250

### CODE REVIEW

**Comment by caphrim007** [comment]
@champain,

Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://f5-ansible.readthedocs.io/en/devel/development/cla-landing.html.

It will cover your contributions to all F5-managed open source projects.
Thanks

**Comment by champain** [comment]
I got signoff on this recently, so I should be able to get this to you shortly.

**Comment by champain** [comment]
Alcon,

I've signed and sent the CLA to ansible_cla@f5.com. Let me know if you need anything else to move forward.

**Comment by champain** [comment]
So the specific fix works in my testing environment when I patch it into ansible 2.2. However, the bigip_selfip module appears to be broken more generally within ansible 2.3, and I can't seem to be able to use it at all there. This is a tough position because you likely have little control over what version of ansible your module gets pulled into, but it puts me in a tough position because I have to patch this module, and then load it into my ansible environment externally. I honestly wish I had the bandwidth to submit a more full-featured pull request, because I think there is just an import path issue preventing this from working in some of the bigip modules and ansible 2.3 since I can see they've changed a lot of the directory structure.

For what it's worth here is the error I'm hitting when I try to load all of the master branch of the f5-ansible module in via a library folder

```
TASK [Provision self-IPs] **********************************************************************************************************************************************************************************
Wednesday 28 June 2017  14:58:46 -0400 (0:00:03.390)       0:00:03.390 ********
failed: [mlb3.proto.arin.net -> dj.pssid.cha.arin.net] (item={'key': u'v6-2001-500-110-727-11', 'value': {u'netmask': u'ffff:ffff:ffff:ffff::', u'vlan': u'prov_external', u'traffic_group': u'traffic-group
-local-only', u'address': u'2001:500:110:727:0::11'}}) => {"failed": true, "item": {"key": "v6-2001-500-110-727-11", "value": {"address": "2001:500:110:727:0::11", "netmask": "ffff:ffff:ffff:ffff::", "tra
ffic_group": "traffic-group-local-only", "vlan": "prov_external"}}, "msg": "The python f5-sdk module is required"}
```

**Comment by caphrim007** [comment]
@champain the modules in this directory are always developed against the latest HEAD of ansible. we don't backport changes into previous releases.

This repo here, as mentioned in the docs and the readme, is not a stable repo, and the recommendation is to upgrade ansible if one wants a module that is in a newer version of ansible.

So if it works in the current devel branch (which will be 2.4) then that meets my expectations.

**Pull request merged**
