### PR TITLE
fixes for  bigip_data_group  and bigip_pool_member issues

### PR DESCRIPTION
**Pull request by RavinderReddyF5**

### CODE REVIEW

**Comment by wojtek0806** [comment]
rebase and post results of full integration test run for bigip_pool_member module. Do this on v12  and v15/16 so we know we haven't broken anything

**Comment by RavinderReddyF5** [comment]
Test results:

```
ansible-playbook -i ~/devsettings/inventory/hosts ~/PycharmProjects/f5-ansible/test/integration/bigip_data_group.yaml
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
[WARNING]: file /Users/chinthalapalli/PycharmProjects/f5-ansible/test/integration/targets/bigip_data_group/tasks/setup.yaml is empty and had no tasks to include
[WARNING]: file /Users/chinthalapalli/PycharmProjects/f5-ansible/test/integration/targets/bigip_data_group/tasks/teardown.yaml is empty and had no tasks to include

PLAY [Metadata of bigip_data_group] **********************************************************************************************************************************************************************

PLAY [Test the bigip_data_group module] ******************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Generic string internal data group file] ****************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic string internal data group file] *********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic string internal data group file - Idempotent check] *********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic string internal data group file - Idempotent check] **************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Update generic string internal data group file] *********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Update generic string internal data group file] **************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Update generic string internal data group file - Idempotent check] **************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Update generic string internal data group file - Idempotent check] *******************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove generic string internal data group] **************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Remove generic string internal data group] *******************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove generic string internal data group - Idempotent check] *******************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Remove generic string internal data group - Idempotent check] ************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic string internal data group list] ****************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic string internal data group list] *********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic string internal data group list - Idempotent check] *********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic string internal data group list - Idempotent check] **************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic string internal data group empty list] **********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic string internal data group empty list] ***************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic string internal data group empty list - Idempotent check] ***************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic string internal data group empty list - Idempotent check] ********************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove Generic string internal data group list] *********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Generic address internal data group file] ***************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic address internal data group file] ********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic address internal data group file - Idempotent check] ********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic address internal data group file - Idempotent check] *************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Update generic address internal data group file] ********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Update generic address internal data group file] *************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Update generic address internal data group file - Idempotent check] *************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Update generic address internal data group file - Idempotent check] ******************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove generic address internal data group] *************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Remove generic address internal data group] ******************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove generic address internal data group - Idempotent check] ******************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Remove generic address internal data group - Idempotent check] ***********************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic address internal data group list] ***************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic address internal data group list] ********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic address internal data group list - Idempotent check] ********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic address internal data group list - Idempotent check] *************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic address internal data group empty list] *********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic address internal data group empty list] **************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic address internal data group empty list - Idempotent check] **************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic address internal data group empty list - Idempotent check] *******************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove Generic address internal data group list] ********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Generic integer internal data group file] ***************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic integer internal data group file] ********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic integer internal data group file - Idempotent check] ********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic integer internal data group file - Idempotent check] *************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Update generic integer internal data group file] ********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Update generic integer internal data group file] *************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Update generic integer internal data group file - Idempotent check] *************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Update generic integer internal data group file - Idempotent check] ******************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove generic integer internal data group] *************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Remove generic integer internal data group] ******************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove generic integer internal data group - Idempotent check] ******************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Remove generic integer internal data group - Idempotent check] ***********************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic integer internal data group list] ***************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic integer internal data group list] ********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic integer internal data group list - Idempotent check] ********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic integer internal data group list - Idempotent check] *************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic integer internal data group empty list] *********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic integer internal data group empty list] **************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic integer internal data group empty list - Idempotent check] **************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic integer internal data group empty list - Idempotent check] *******************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove Generic integer internal data group list] ********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Generic string external data group file] ****************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic string external data group file] *********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic string external data group file - Idempotent check] *********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic string external data group file - Idempotent check] **************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Update generic string external data group file] *********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Update generic string external data group file] **************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Update generic string external data group file - Idempotent check] **************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Update generic string external data group file - Idempotent check] *******************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove generic string external data group (retain DG file)] *********************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Remove generic string external data group (retain DG file)] **************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove generic string external data group (retain DG file) - Idempotent check] **************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Remove generic string external data group (retain DG file) - Idempotent check] *******************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove file used in generic string external data group] *************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Remove file used in generic string external data group] ******************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove file used in generic string external data group - Idempotent check] ******************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Remove file used in generic string external data group - Idempotent check] ***********************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic string external data group list] ****************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic string external data group list] *********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic string external data group list - Idempotent check] *********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic string external data group list - Idempotent check] **************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic string external data group empty list - Expected failure] ***************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic string external data group empty list - Expected success] ********************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove Generic string external data group list] *********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Generic address external data group file] ***************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic address external data group file] ********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic address external data group file - Idempotent check] ********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic address external data group file - Idempotent check] *************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Update generic address external data group file] ********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Update generic address external data group file] *************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Update generic address external data group file - Idempotent check] *************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Update generic address external data group file - Idempotent check] ******************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove generic address external data group (retain DG file)] ********************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Remove generic address external data group (retain DG file)] *************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove generic address external data group (retain DG file) - Idempotent check] *************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Remove generic address external data group (retain DG file) - Idempotent check] ******************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove file used in generic address external data group] ************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Remove file used in generic address external data group] *****************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove file used in generic address external data group - Idempotent check] *****************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Remove file used in generic address external data group - Idempotent check] **********************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic address external data group list] ***************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic address external data group list] ********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic address external data group list - Idempotent check] ********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic address external data group list - Idempotent check] *************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic address external data group empty list - Expected failure] **************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic address external data group empty list - Expected success] *******************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove Generic address external data group list] ********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : SR1-7089774221-Support datagroup with only key] *********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert SR1-7089774221-Support datagroup with only key] **************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : SR1-7089774221-Support datagroup with only key - Idempotent check] **************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : SR1-7089774221-Support datagroup with only key - Idempotent check] **************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove datagroup external-dg-keyonly(SR1-7089774221) (retain DG file)] **********************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Remove datagroup external-dg-keyonly(SR1-7089774221) (retain DG file)] ***************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove datagroup external-dg-keyonly(SR1-7089774221) (retain DG file) - Idempotent check] ***************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Remove datagroup external-dg-keyonly(SR1-7089774221) (retain DG file) - Idempotent check] ********************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove file used in external-dg-keyonly] ****************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Remove file used in external-dg-keyonly] *********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove file used in external-dg-keyonly - Idempotent check] *********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Remove file used in external-dg-keyonly - Idempotent check] **************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic integer external data group file] ***************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic integer external data group file] ********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic integer external data group file - Idempotent check] ********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic integer external data group file - Idempotent check] *************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Update generic integer external data group file] ********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Update generic integer external data group file] *************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Update generic integer external data group file - Idempotent check] *************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Update generic integer external data group file - Idempotent check] ******************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove generic integer external data group (retain DG file)] ********************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Remove generic integer external data group (retain DG file)] *************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove generic integer external data group (retain DG file) - Idempotent check] *************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Remove generic integer external data group (retain DG file) - Idempotent check] ******************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove file used in generic integer external data group] ************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Remove file used in generic integer external data group] *****************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove file used in generic integer external data group - Idempotent check] *****************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Remove file used in generic integer external data group - Idempotent check] **********************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic integer external data group list] ***************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic integer external data group list] ********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic integer external data group list - Idempotent check] ********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic integer external data group list - Idempotent check] *************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic integer external data group empty list - Expected failure] **************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic integer external data group empty list - Expected success] *******************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Remove Generic integer external data group list] ********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 00652 - Create a data group with duplicate strings] ***********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 00652 - Assert Create a data group with duplicate strings] ****************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 00815 - Create an upper case Data Group] **********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 00815 - Assert Create an upper case Data Group] ***************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 00815 - Create an upper case Data Group - Idempotent check] ***************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 00815 - Assert Create an upper case Data Group - Idempotent check] ********************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 00815 - Remove external data group list] **********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 01083 - Generic string internal data group file] **************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 01083 - Assert Generic string internal data group file] *******************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01083 - Generic string internal data group file - Idempotent check] *******************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 01083 - Assert Generic string internal data group file - Idempotent check] ************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01083 - Change description] ***********************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 01083 - Assert Change description] ****************************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01083 - Change description - Idempotent check] ****************************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 01083 - Assert Change description - Idempotent check] *********************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01083 - Change description - none] ****************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 01083 - Assert Change description - none] *********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01083 - Change description - none - Idempotent check] *********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 01083 - Assert Change description - none - Idempotent check] **************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01083 - Change description - empty - Idempotent check] ********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 01083 - Assert Change description - empty - Idempotent check] *************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic string external data group file] ****************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Assert Generic string external data group file] *********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Generic string external data group file - Idempotent check] *********************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Assert Generic string external data group file - Idempotent check] **************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01083 - Change external description] **************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 01083 - Assert Change external description] *******************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01083 - Change external description - Idempotent check] *******************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 01083 - Assert Change external description - Idempotent check] ************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01083 - Change external description - none] *******************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 01083 - Assert Change external description - none] ************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01083 - Change external description - none - Idempotent check] ************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 01083 - Assert Change external description - none - Idempotent check] *****************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01083 - Change external description - empty - Idempotent check] ***********************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 01083 - Assert Change external description - empty - Idempotent check] ****************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01083 - Remove data groups] ***********************************************************************************************************************************************
changed: [bigip1] => (item={'name': 'external-dg1', 'internal': False, 'delete_data_group_file': True})
changed: [bigip1] => (item={'name': 'internal-dg1', 'internal': True})

TASK [bigip_data_group : Issue 1210 - Create Route Domain] ***********************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 1210 - Create Other partition] ********************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 1210 - Create datagroup on Other partition] *******************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 1210 - Assert Create datagroup on Other partition] ************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 1210 - Create datagroup on Other partition - Idempotent check] ************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 1210 - Assert Create datagroup on Other partition - Idempotent check] *****************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 1210 - Remove datagroup on Other partition] *******************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 1210 - Remove Other partition] ********************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 1210 - Remove Route Domain] ***********************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 1346 - Create Route Domain] ***********************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 1346 - Create Other partition] ********************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 1346 - Create datagroup on Other partition] *******************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 1346 - Assert Create datagroup on Other partition] ************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 1346 - Create datagroup on Other partition - Idempotent check] ************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 1346 - Assert Create datagroup on Other partition - Idempotent check] *****************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 1346 - Remove datagroup on Other partition] *******************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 1346 - Remove Other partition] ********************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 1346 - Remove Route Domain] ***********************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 01607 - Create a data group of addresses] *********************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 01607 - Assert Create a data group of addresses] **************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01607 - Create a data group of addresses - Idempotent check] **************************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 01607 - Assert Create a data group of addresses - Idempotent check] *******************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01607 - Remove internal datagroup] ****************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 01607 - Assert Remove internal datagroup] *********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01607 - Create external data group of addresses] **************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 01607 - Assert Create external data group of addresses] *******************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01607 - Create external data group of addresses - Idempotent check] *******************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 01607 - Assert Create external data group of addresses - Idempotent check] ************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01607 - Remove external datagroup] ****************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 01607 - Assert Remove external datagroup] *********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01587 - Create a data group with a question mark] *************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 01587 - Assert Create a data group with a question mark] ******************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01587 - Create a data group with a question mark - Idempotent check] ******************************************************************************************************
ok: [bigip1]

TASK [bigip_data_group : Issue 01587 - Assert Create a data group with a question mark - Idempotent check] ***********************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [bigip_data_group : Issue 01587 - Remove internal datagroup] ****************************************************************************************************************************************
changed: [bigip1]

TASK [bigip_data_group : Issue 01587 - Assert Remove internal datagroup] *********************************************************************************************************************************
ok: [bigip1] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY RECAP ***********************************************************************************************************************************************************************************************
bigip1                     : ok=217  changed=66   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


```

**Comment by amolari** [comment]
@RavinderReddyF5 is "Fix for bigip_pool_member aggregate fails to member comparison" for INFRAANO-234?

**Comment by RavinderReddyF5** [comment]
@amolari no i did not fix INFRAANO-234

**Comment by trinaths** [comment]
@amolari - INFRAANO-243 is not related to this issue.

**Pull request merged**
