### PR TITLE
Fixes #1587

### LINKED ISSUE #1587: bigip_data_group is changing the data group every run when a "?" is in a value
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_data_group

##### ANSIBLE VERSION

```
ansible 2.9.1
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.0.6
  Build       0.0.9
  Edition     Point Release 6
  Date        Fri Jun 21 21:06:44 PDT 2019

```

##### CONFIGURATION

```
$ cat ansible.cfg 
[defaults]
retry_files_enabled = False
host_key_checking=False
ask_vault_pass=true
```

##### OS / ENVIRONMENT

RHEL7

##### SUMMARY

In case a data group record contains a '?' character ansible changes the data group with every run.
The root cause is that the '?' character in the value that we get from the F5 box gets escaped with '\\' in front. See more information below in the Extra debug information section.

##### STEPS TO REPRODUCE

```
$ cat playbook.yaml 
---

- name: Configuring LBs including hypervisors and vCMP guests
  hosts: all
  connection: local
  gather_facts: False

# enabling this role would use the bleeding edge modules from f5 directly. Not recommended in prod but needed when you report a bug!
  roles:
    - role: f5devcentral.f5ansible

  vars:
    provider:
      password: "{{ f5_password }}"
      server: "{{ ansible_host }}"
      user: "{{ f5_username }}"
      validate_certs: "{{ validate_certs }}"
      server_port: "{{ f5_server_port }}"

  tasks:
    - name: Configure data groups on masters
      bigip_data_group:
        name: "test_bugerport_datagroup"
        type: "string"
        internal: "yes"
        records:
          - key: "test"
            value: "something with ? inside"
        state: present
        provider: "{{ provider }}"

# vim: tabstop=2 expandtab
```
##### Extra debug information
In order to get a bit more debug info I've modified the module so it writes out the records got from the F5 box and the records that are in ansible into a file in /tmp:**
```
[randomuser@randomhost data_group_issue]$ diff -rupN /home/randomuser/EL7/.ansible/roles/f5devcentral.f5ansible/library/bigip_data_group.py.orig /home/randomuser/EL7/.ansible/roles/f5devcentral.f5ansible/library/bigip_data_group.py
--- /home/randomuser/EL7/.ansible/roles/f5devcentral.f5ansible/library/bigip_data_group.py.orig	2019-12-05 16:10:19.611534000 +0100
+++ /home/randomuser/EL7/.ansible/roles/f5devcentral.f5ansible/library/bigip_data_group.py	2019-12-05 16:15:19.265065000 +0100
@@ -784,6 +784,13 @@ class Difference(object):
         # and we would never want to do a comparison of such huge files.
         #
         # Therefore, comparison is no-op if the DG being worked with is an external DG.
+
+        with open('/tmp/records_%s.txt' % id(self), 'w') as f:
+            for item in self.want.records:
+                f.write("%s\n" % item)
+            for item in self.have.records:
+                f.write("%s\n" % item)
+
         if self.want.internal is False:
             return None
         if self.have.records is None and self.want.records == []:
[randomuser@randomhost data_group_issue]$
```

And the results after two run are:
```
[randomuser@randomhost data_group_issue]$ cat /tmp/records_140670474430928.txt 
{'data': u'something with ? inside', 'name': u'test'}
{u'data': u'something with \\? inside', u'name': u'test'}
```

##### EXPECTED RESULTS

ansible does not modify the config as the data group did not change

##### ACTUAL RESULTS

Ansible modifies the data group each and every time due to the additional \\ characters (see above in the records file)

```
[randomuser@randomhost data_group_issue]$ ansible-playbook -vvv -i inventory/hosts playbook.yaml 
ansible-playbook 2.9.1
  config file = /home/randomuser/EL7/local/ansible/data_group_issue/ansible.cfg
  configured module search path = [u'/home/randomuser/EL7/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /home/randomuser/EL7/local/ansible/data_group_issue/ansible.cfg as config file
Vault password: 
host_list declined parsing /home/randomuser/EL7/local/ansible/data_group_issue/inventory/hosts as it did not pass its verify_file() method
script declined parsing /home/randomuser/EL7/local/ansible/data_group_issue/inventory/hosts as it did not pass its verify_file() method
auto declined parsing /home/randomuser/EL7/local/ansible/data_group_issue/inventory/hosts as it did not pass its verify_file() method
Parsed /home/randomuser/EL7/local/ansible/data_group_issue/inventory/hosts inventory source with ini plugin

PLAYBOOK: playbook.yaml *******************************************************************************************************************************************************************************************
1 plays in playbook.yaml

PLAY [Configuring LBs including hypervisors and vCMP guests] ******************************************************************************************************************************************************
META: ran handlers

TASK [f5devcentral.f5ansible : Check ansible version] *************************************************************************************************************************************************************
task path: /home/randomuser/EL7/.ansible/roles/f5devcentral.f5ansible/tasks/main.yaml:2
skipping: [lbx01.example.com] => {}

TASK [Configure data groups on masters] ***************************************************************************************************************************************************************************
task path: /home/randomuser/EL7/local/ansible/data_group_issue/playbook.yaml:21
<lbx01.example.com> ESTABLISH LOCAL CONNECTION FOR USER: randomuser
<lbx01.example.com> EXEC /bin/sh -c 'echo ~randomuser && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558369.92-15272749332819 `" && echo ansible-tmp-1575558369.92-15272749332819="` echo /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558369.92-15272749332819 `" ) && sleep 0'
<lbx01.example.com> Attempting python interpreter discovery
<lbx01.example.com> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /home/randomuser/EL7/.ansible/roles/f5devcentral.f5ansible/library/bigip_data_group.py
<lbx01.example.com> PUT /home/randomuser/EL7/.ansible/tmp/ansible-local-70682jhbweH/tmp05LbrV TO /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558369.92-15272749332819/AnsiballZ_bigip_data_group.py
<lbx01.example.com> EXEC /bin/sh -c 'chmod u+x /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558369.92-15272749332819/ /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558369.92-15272749332819/AnsiballZ_bigip_data_group.py && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c '/usr/bin/python /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558369.92-15272749332819/AnsiballZ_bigip_data_group.py && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c 'rm -f -r /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558369.92-15272749332819/ > /dev/null 2>&1 && sleep 0'
changed: [lbx01.example.com] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "delete_data_group_file": null, 
            "description": null, 
            "external_file_name": null, 
            "internal": true, 
            "name": "test_bugerport_datagroup", 
            "partition": "Common", 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "lbx01.example.com", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "records": [
                {
                    "key": "test", 
                    "value": "something with ? inside"
                }
            ], 
            "records_src": null, 
            "separator": ":=", 
            "state": "present", 
            "type": "string"
        }
    }, 
    "records": [
        {
            "data": "something with ? inside", 
            "name": "test"
        }
    ], 
    "type": "string"
}
META: ran handlers
META: ran handlers

PLAY RECAP ********************************************************************************************************************************************************************************************************
lbx01.example.com          : ok=1    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   

[randomuser@randomhost data_group_issue]$ ansible-playbook -vvv -i inventory/hosts playbook.yaml 
ansible-playbook 2.9.1
  config file = /home/randomuser/EL7/local/ansible/data_group_issue/ansible.cfg
  configured module search path = [u'/home/randomuser/EL7/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /home/randomuser/EL7/local/ansible/data_group_issue/ansible.cfg as config file
Vault password: 
host_list declined parsing /home/randomuser/EL7/local/ansible/data_group_issue/inventory/hosts as it did not pass its verify_file() method
script declined parsing /home/randomuser/EL7/local/ansible/data_group_issue/inventory/hosts as it did not pass its verify_file() method
auto declined parsing /home/randomuser/EL7/local/ansible/data_group_issue/inventory/hosts as it did not pass its verify_file() method
Parsed /home/randomuser/EL7/local/ansible/data_group_issue/inventory/hosts inventory source with ini plugin

PLAYBOOK: playbook.yaml *******************************************************************************************************************************************************************************************
1 plays in playbook.yaml

PLAY [Configuring LBs including hypervisors and vCMP guests] ******************************************************************************************************************************************************
META: ran handlers

TASK [f5devcentral.f5ansible : Check ansible version] *************************************************************************************************************************************************************
task path: /home/randomuser/EL7/.ansible/roles/f5devcentral.f5ansible/tasks/main.yaml:2
skipping: [lbx01.example.com] => {}

TASK [Configure data groups on masters] ***************************************************************************************************************************************************************************
task path: /home/randomuser/EL7/local/ansible/data_group_issue/playbook.yaml:21
<lbx01.example.com> ESTABLISH LOCAL CONNECTION FOR USER: randomuser
<lbx01.example.com> EXEC /bin/sh -c 'echo ~randomuser && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558428.91-45586176224322 `" && echo ansible-tmp-1575558428.91-45586176224322="` echo /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558428.91-45586176224322 `" ) && sleep 0'
<lbx01.example.com> Attempting python interpreter discovery
<lbx01.example.com> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /home/randomuser/EL7/.ansible/roles/f5devcentral.f5ansible/library/bigip_data_group.py
<lbx01.example.com> PUT /home/randomuser/EL7/.ansible/tmp/ansible-local-70796biDZ_J/tmpd1_xRZ TO /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558428.91-45586176224322/AnsiballZ_bigip_data_group.py
<lbx01.example.com> EXEC /bin/sh -c 'chmod u+x /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558428.91-45586176224322/ /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558428.91-45586176224322/AnsiballZ_bigip_data_group.py && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c '/usr/bin/python /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558428.91-45586176224322/AnsiballZ_bigip_data_group.py && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c 'rm -f -r /home/randomuser/EL7/.ansible/tmp/ansible-tmp-1575558428.91-45586176224322/ > /dev/null 2>&1 && sleep 0'
changed: [lbx01.example.com] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "delete_data_group_file": null, 
            "description": null, 
            "external_file_name": null, 
            "internal": true, 
            "name": "test_bugerport_datagroup", 
            "partition": "Common", 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "lbx01.example.com", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "records": [
                {
                    "key": "test", 
                    "value": "something with ? inside"
                }
            ], 
            "records_src": null, 
            "separator": ":=", 
            "state": "present", 
            "type": "string"
        }
    }, 
    "records": [
        {
            "data": "something with ? inside", 
            "name": "test"
        }
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP ********************************************************************************************************************************************************************************************************
lbx01.example.com          : ok=1    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   

[randomuser@randomhost data_group_issue]$

```

### PR DESCRIPTION
**Pull request by nitinthewiz**
I looked far and wide for a solution such that we could use python's decode functionality, but we're handicapped by the fact that BIG-IP adds two backslashes instead of one. This is necessary to display the config in tmsh.

So, the safest way to do this is to do a regex replace.

Currently, only dealing with the situation where the string '\\?' shows up. If in the future, we find more corner cases, we should convert this into a function, and then perhaps a library function.

### CODE REVIEW

**Comment by nitinthewiz** [comment]
Testing done for v13-15 and it works. v12 has an error that's unrelated. I'll file an internal ticket for that and follow up. Will keep that separate from this check in though.

BIGIP 13.x

Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.3.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Tue Nov  5 18:45:57 PST 2019

PLAY RECAP ******************************************************************************************************************************
bigip4                     : ok=205  changed=63   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   



BIGIP 14.x

Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Tue Nov  5 10:09:50 PST 2019


Ansible result - 

PLAY RECAP ******************************************************************************************************************************
bigip2                     : ok=205  changed=63   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   





BIGIP 15.x

Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.0
  Build       0.0.31
  Edition     Final
  Date        Thu Nov 21 05:44:00 PST 2019


PLAY RECAP ******************************************************************************************************************************
bigip3                     : ok=205  changed=63   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by wojtek0806** [comment]
this needs to be fixed as well, what is the error?

**Comment by nitinthewiz** [comment]
> this needs to be fixed as well, what is the error?

"Generic string internal data group empty list" fails in [this basic test list](https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/targets/bigip_data_group/tasks/internal/string.yaml).

This is wholly unrelated. The test fails whether my code is there or not. Like I said, I can investigate as part of a separate issue.

**Comment by wojtek0806** [comment]
no if you find a bug fix this in the same PR, it took me entire 3 mins to find the problem and provide a fix, once its merged you will need to rebase

**Comment by wojtek0806** [comment]
fix was merged yesterday

**Pull request merged**
