### PR TITLE
Adding cli transport changes

### PR DESCRIPTION
**Pull request by jmighion**

### CODE REVIEW

**Comment by caphrim007** [comment]
is it ok if I add transport to the argument_spec in the module to prevent non-2.5 ansible users of this repo from blowing up?

**Comment by jmighion** [comment]
Yeah good call. Want me to do that?

**Comment by caphrim007** [comment]
@jmighion go for it. Also fix the reference to `f5api` in it

**Comment by caphrim007** [comment]
lgtm

**Pull request merged**
